plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id 'kotlin-kapt'
    alias(libs.plugins.dagger.hilt)
}

android {
    namespace 'com.adrielmadrigal.androidnews'
    compileSdk 34

    defaultConfig {
        applicationId "com.adrielmadrigal.androidnews"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {
            // Configuration for the debug build type
            buildConfigField "String", "FLAVOR", "\"debug\""
        }
        release {
            // Configuration for the release build type
            buildConfigField "String", "FLAVOR", "\"production\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        composeDebug {
            buildConfigField "String", "FLAVOR", "\"composePreview\""
            composeOptions {
                kotlinCompilerExtensionVersion '1.3.2'
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
        buildConfig true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation platform(libs.jetbrains.kotlin)
    implementation(libs.androidx.core.ktx)
    implementation(libs.bundles.androidx.lifecycle)
    implementation(libs.bundles.androidx.compose)
    implementation(libs.bundles.retrofit2)
    implementation(libs.bundles.rxjava)
    implementation(libs.koin.compose)
    implementation(libs.okhttp3.logging)
    implementation(libs.dagger.hilt.android)

    testImplementation(libs.junit)
    testImplementation(libs.rxjava.core)
    testImplementation(libs.rxjava.rxandroid)

    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.test.implementation)
    androidTestImplementation(libs.androidx.compose.ui.test.junit)

    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    kapt(libs.dagger.hilt.compiler)
}

kapt {
    correctErrorTypes true
}