plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
}

apply from: '../dependencies.gradle'

android {
    namespace 'com.adrielmadrigal.androidnews'
    compileSdk 34

    defaultConfig {
        applicationId "com.adrielmadrigal.androidnews"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {
            // Configuration for the debug build type
            buildConfigField "String", "FLAVOR", "\"debug\""
        }
        release {
            // Configuration for the release build type
            buildConfigField "String", "FLAVOR", "\"production\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        composeDebug {
            buildConfigField "String", "FLAVOR", "\"composePreview\""
            composeOptions {
                kotlinCompilerExtensionVersion '1.3.2'
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
        buildConfig true
    }
//    composeOptions {
//        kotlinCompilerExtensionVersion '1.3.2'
//    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation androidXCoreKtx
    implementation androidXLifecycleViewModelKtx
    implementation androidXLifecycleViewModelCompose
    implementation androidXLifecycleViewModelSavedState
    implementation androidXLifecycleLivedataKtx
    implementation androidXLifecycleRuntimeKtx
    implementation androidXLifecycleRuntimeCompose
    implementation koinCompose
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.10" // Kotlin version for stdlib
//    implementation platform(jetbrainKotlinBom)
    implementation androidXActivityCompose
    implementation androidXComposeUI
    implementation androidXComposeUIGraphics
    implementation androidXComposeUIToolingPreview
    implementation androidXComposeMaterial
    implementation androidXComposeRuntime
    implementation androidXComposeRuntimeLivedata
    implementation androidXComposeRuntimeRxJava3
    implementation retrofit2
    implementation retrofit2AdapterRxJava3
    implementation retrofit2ConverterGson
    implementation rxjavaRxKotlin
    implementation rxjavaRxAndroid
    implementation rxjavaRxJava
    implementation okHttp3Logging
//    implementation daggerHiltAndroid

    testImplementation junit
    testImplementation rxjavaRxJava
    testImplementation rxjavaRxAndroid
    testImplementation mockkCore
    testImplementation mockkAndroid
    testImplementation mockkAgent

    androidTestImplementation androidXTestJunit
    androidTestImplementation androidXTestEspressoCore
    androidTestImplementation androidXComposeUITestJunit
    androidTestImplementation androidXTestRules
    androidTestImplementation androidXTestRunner
//    androidTestImplementation daggerHiltAndroidTesting

    debugImplementation androidXComposeUITooling
    debugImplementation androidXComposeUITestManifest

//    kapt daggerHiltCompiler
//    kaptAndroidTest daggerHiltAndroidCompiler

//    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.0')
//    implementation platform('androidx.compose:compose-bom:2022.10.00')

    implementation 'com.google.dagger:hilt-android:2.51.1'
    kapt 'com.google.dagger:hilt-compiler:2.51.1'

    // For instrumentation tests
    androidTestImplementation  'com.google.dagger:hilt-android-testing:2.51.1'
    kaptAndroidTest 'com.google.dagger:hilt-compiler:2.51.1'

    // For local unit tests
    testImplementation 'com.google.dagger:hilt-android-testing:2.51.1'
    kaptTest 'com.google.dagger:hilt-compiler:2.51.1'
}

kapt {
    correctErrorTypes true
}